In [2]:
import numpy as np

In [3]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b)

0

In [6]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [8]:
X=np.array([[1,0,1],[2,2,2]])
out=X[0:2,2]
out

array([1, 2])

In [9]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [10]:
var='01234567'
print(var[::2])

0246


In [11]:
x=float(5)
print(x)

5.0


In [12]:
1/2

0.5

In [13]:
2//3

0

In [14]:
x="7"
if(x!=1):
    print('How are you?')

How are you?
